using WoofBnB.Infrastructure.Security;

namespace WoofBnB.UnitTests.Security;

/// <summary>
/// Cross-compatibility with server/src/utils/crypto/password.js. NodeProducedHash below
/// is a REAL hash, generated by running:
///   node -e "require('bcrypt').hash('TestPassword123', 10).then(h => console.log(h))"
/// from inside server/ (using the actual npm bcrypt package Node ships), not a hand-typed
/// or assumed value — this is the exact compatibility question the migration hinges on.
/// </summary>
public class BCryptPasswordHasherTests
{
    private const string NodeProducedHash = "$2b$10$vo3NwqoXwAYUeqPuCslYRuwO7TFIfOz4hVppKGNUobQpbHis8dQC.";
    private const string CorrectPassword = "TestPassword123";

    private readonly BCryptPasswordHasher _hasher = new(workFactor: 10);

    [Fact]
    public void Verify_NodeProducedHash_WithCorrectPassword_Succeeds()
    {
        Assert.True(_hasher.Verify(CorrectPassword, NodeProducedHash));
    }

    [Fact]
    public void Verify_NodeProducedHash_WithIncorrectPassword_Fails()
    {
        Assert.False(_hasher.Verify("WrongPassword456", NodeProducedHash));
    }

    [Fact]
    public void Hash_ProducesA2bPrefixedHash_ThatNodeBcryptWouldAlsoAccept()
    {
        var hash = _hasher.Hash(CorrectPassword);

        Assert.StartsWith("$2", hash);
        Assert.True(_hasher.Verify(CorrectPassword, hash));
    }

    [Fact]
    public void Hash_ThenVerify_RoundTrips()
    {
        var hash = _hasher.Hash("AnotherPassword789");

        Assert.True(_hasher.Verify("AnotherPassword789", hash));
        Assert.False(_hasher.Verify("AnotherPassword789wrong", hash));
    }
}
